<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicEndpoints" Version="0.0.0-dynamic-endpoints-version" />
    <PackageReference Include="DynamicEndpoints.EntityFrameworkCore" Version="0.0.0-dynamic-endpoints-version" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
<!--#if (!NoSwagger) -->
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
<!--#endif -->
  </ItemGroup>

</Project>
