using DynamicEndpoints;
using DynamicEndpointsApp.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("Default")));

builder.Services
    .AddDynamicEndpoints(options =>
    {
        // Dynamic routes can't take over the static parts of the application.
        options.ReservedPrefixes.Add("/api");
        options.ReservedPrefixes.Add("/openapi");
#if (!NoSwagger)
        options.ReservedPrefixes.Add("/swagger");
#endif
        options.OpenApi.Title = "DynamicEndpointsApp – dynamic endpoints";
    })
    // Every processor, validator and seeder of this project: GreetingProcessor, DemoEndpointsSeeder, …
    .AddFromAssemblyContaining<Program>()
    .UseEntityFrameworkStore<AppDbContext>();

// OpenAPI document of the static API (the admin API) – the dynamic one is generated by DynamicEndpoints.
builder.Services.AddOpenApi();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    // Creates the SQLite database on first start. Switch to EF Core migrations (and .MigrateOnStartup<AppDbContext>())
    // once the schema has to evolve.
    await scope.ServiceProvider.GetRequiredService<AppDbContext>().Database.EnsureCreatedAsync();
}

app.MapDynamicEndpoints();

// Generic admin REST API to create, change and delete endpoints at runtime.
// Secure it before going live, e.g. .RequireAuthorization("admin").
app.MapDynamicEndpointsAdmin("/api/admin/endpoints");
#if (!NoAdminUI)

// The admin panel on top of it: list, editor, drafts, history and a "Try" console. Secure it like the admin API.
app.MapDynamicEndpointsAdminUI("/admin", adminApiPath: "/api/admin/endpoints", options =>
{
    options.Title = "DynamicEndpointsApp – endpoints";
    options.OpenApiUrl = "/openapi/dynamic.json";
#if (!NoSwagger)
    options.SwaggerUrl = "/swagger";
#endif
});
#endif

app.MapDynamicEndpointsOpenApi("/openapi/dynamic.json");
app.MapOpenApi("/openapi/{documentName}.json");

#if (!NoSwagger)
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/openapi/dynamic.json", "Dynamic endpoints");
    options.SwaggerEndpoint("/openapi/v1.json", "Admin API");
    options.DocumentTitle = "DynamicEndpointsApp – Swagger UI";
});

#endif

#if (!NoAdminUI)
app.MapGet("/", () => Results.Redirect("/admin/")).ExcludeFromDescription();
#elif (!NoSwagger)
app.MapGet("/", () => Results.Redirect("/swagger")).ExcludeFromDescription();
#else
app.MapGet("/", () => Results.Redirect("/openapi/dynamic.json")).ExcludeFromDescription();
#endif

app.Run();

public partial class Program;
