using DynamicEndpoints;
using DynamicEndpoints.Sample;
using DynamicEndpoints.Sample.Data;
using DynamicEndpoints.Sample.Greetings;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("Default") ?? "Data Source=dynamic-endpoints.db"));

builder.Services
    .AddDynamicEndpoints(options =>
    {
        options.ReservedPrefixes.Add("/admin");
        options.ReservedPrefixes.Add("/swagger");
        options.ReservedPrefixes.Add("/openapi");
        options.ReservedPrefixes.Add("/api");
        options.OpenApi.Title = "Sample dynamic API";
        options.OpenApi.Description = "Endpoints defined at runtime in the admin panel.";
        // Picks up changes made by other instances sharing the database.
        options.RefreshInterval = TimeSpan.FromSeconds(30);
    })
    // All processors, validators and seeders of this project – EchoProcessor, NipValidator, SampleEndpointsSeeder, …
    .AddFromAssemblyContaining<Program>()
    // All FluentValidation validators – BookingRequestValidator -> "booking-request", IbanValidator -> "iban"
    .AddFluentValidatorsFromAssemblyContaining<Program>()
    .AddProcessor("clock", request =>
    {
        var zoneId = request.Get<string>("timeZone") ?? "UTC";
        if (!TimeZoneInfo.TryFindSystemTimeZoneById(zoneId, out var zone))
        {
            return Results.ValidationProblem(new Dictionary<string, string[]> { ["timeZone"] = [$"Unknown time zone '{zoneId}'."] });
        }

        var now = DateTimeOffset.UtcNow;
        return Results.Ok(new { timeZone = zone.Id, utc = now, local = TimeZoneInfo.ConvertTime(now, zone) });
    }, "Returns the current time in the 'timeZone' parameter (IANA or Windows id).")
    .UseEntityFrameworkStore<AppDbContext>();

// Own feature service that manages dynamic endpoints through the injected IDynamicEndpointManager.
builder.Services.AddScoped<GreetingEndpointsService>();

// OpenAPI document of the static (admin) API – the dynamic one is generated by the library.
builder.Services.AddOpenApi();

var app = builder.Build();

// Demo only – use migrations in a real application.
await SampleDatabase.EnsureCreatedAsync(app.Services);

app.UseDefaultFiles();
app.UseStaticFiles();

app.MapGet("/", () => Results.Redirect("/admin/")).ExcludeFromDescription();

app.MapDynamicEndpoints();
app.MapDynamicEndpointsAdmin("/api/admin/endpoints"); // generic admin API – .RequireAuthorization("admin") in real life
app.MapGreetingsApi();                                  // purpose-built API using the injected manager
app.MapDynamicEndpointsOpenApi("/openapi/dynamic.json");
app.MapOpenApi("/openapi/{documentName}.json");

app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/openapi/dynamic.json", "Dynamic endpoints");
    options.SwaggerEndpoint("/openapi/v1.json", "Admin API");
    options.DocumentTitle = "Dynamic endpoints – Swagger UI";
});

app.Run();

public partial class Program;
