using DynamicEndpoints;
using DynamicEndpoints.Sample;
using DynamicEndpoints.Sample.Data;
using DynamicEndpoints.Sample.Demo;
using DynamicEndpoints.Sample.Greetings;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// OpenTelemetry with the per-endpoint metrics and traces, health checks, service discovery (DynamicEndpoints.ServiceDefaults).
builder.AddServiceDefaults();
var demo = builder.AddDemoMode();

// SQLite by default; PostgreSQL when there's a "dynamicendpoints" connection string (the Aspire AppHost, docker compose).
var postgres = builder.Configuration.GetConnectionString("dynamicendpoints");
builder.Services.AddDbContext<AppDbContext>(options =>
{
    if (postgres is not null)
    {
        options.UseNpgsql(postgres);
    }
    else
    {
        options.UseSqlite(builder.Configuration.GetConnectionString("Default") ?? "Data Source=dynamic-endpoints.db");
    }
});

var dynamicEndpoints = builder.Services
    .AddDynamicEndpoints(options =>
    {
        options.ReservedPrefixes.Add("/admin");
        options.ReservedPrefixes.Add("/swagger");
        options.ReservedPrefixes.Add("/openapi");
        options.ReservedPrefixes.Add("/api");
        options.OpenApi.Title = "Sample dynamic API";
        options.OpenApi.Description = "Endpoints defined at runtime in the admin panel.";
        // Picks up changes made by other instances sharing the database.
        options.RefreshInterval = TimeSpan.FromSeconds(30);
    })
    // All processors, validators and seeders of this project – EchoProcessor, NipValidator, SampleEndpointsSeeder, …
    .AddFromAssemblyContaining<Program>()
    // All FluentValidation validators – BookingRequestValidator -> "booking-request", IbanValidator -> "iban"
    .AddFluentValidatorsFromAssemblyContaining<Program>()
    .AddProcessor("clock", request =>
    {
        var zoneId = request.Get<string>("timeZone") ?? "UTC";
        if (!TimeZoneInfo.TryFindSystemTimeZoneById(zoneId, out var zone))
        {
            return Results.ValidationProblem(new Dictionary<string, string[]> { ["timeZone"] = [$"Unknown time zone '{zoneId}'."] });
        }

        var now = DateTimeOffset.UtcNow;
        return Results.Ok(new { timeZone = zone.Id, utc = now, local = TimeZoneInfo.ConvertTime(now, zone) });
    }, "Returns the current time in the 'timeZone' parameter (IANA or Windows id).")
    .UseEntityFrameworkStore<AppDbContext>();

// Several instances: Redis tells the others about a change right away (polling above stays the fallback).
if (builder.Configuration.GetConnectionString("redis") is { Length: > 0 } redis)
{
    dynamicEndpoints.UseRedisChangeNotifications(redis);
}

// Own feature service that manages dynamic endpoints through the injected IDynamicEndpointManager.
builder.Services.AddScoped<GreetingEndpointsService>();

// OpenAPI document of the static (admin) API – the dynamic one is generated by the library.
builder.Services.AddOpenApi();

var app = builder.Build();

// Demo only – use migrations in a real application.
await SampleDatabase.EnsureCreatedAsync(app.Services);

if (demo.Enabled)
{
    app.UseRateLimiter();
}

app.MapGet("/", () => Results.Redirect("/admin/")).ExcludeFromDescription();
app.MapDefaultEndpoints();

app.MapDynamicEndpoints();
app.MapDynamicEndpointsAdmin("/api/admin/endpoints"); // generic admin API – .RequireAuthorization("admin") in real life
app.MapDynamicEndpointsAdminUI("/admin", adminApiPath: "/api/admin/endpoints", o =>  // the panel (DynamicEndpoints.AdminUI)
{
    o.Title = demo.Enabled ? $"Dynamic Endpoints – live demo, resets every {demo.ResetInterval.TotalMinutes:0} min" : "Dynamic Endpoints";
    o.SwaggerUrl = "/swagger";
    o.OpenApiUrl = "/openapi/dynamic.json";
});
app.MapGreetingsApi();                                  // purpose-built API using the injected manager
app.MapDynamicEndpointsOpenApi("/openapi/dynamic.json");
app.MapOpenApi("/openapi/{documentName}.json");

app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/openapi/dynamic.json", "Dynamic endpoints");
    options.SwaggerEndpoint("/openapi/v1.json", "Admin API");
    options.DocumentTitle = "Dynamic endpoints – Swagger UI";
});

app.Run();

public partial class Program;
