// 01 – Quick start: the minimum to get runtime-defined endpoints with an admin panel and Swagger UI.
// The same setup as the README quick start and `dotnet new dynamic-endpoints`.
//
//   dotnet run --project samples/01-QuickStart      → http://localhost:5101/admin/

using DynamicEndpoints;
using DynamicEndpoints.Samples.QuickStart;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// 1. Your own DbContext stores the definitions (AppDbContext.cs). SQLite file from appsettings.json: quickstart.db in the
//    directory you start the app from.
builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlite(builder.Configuration.GetConnectionString("Default")));

// 2. DynamicEndpoints: options, building blocks and the store.
builder.Services
    .AddDynamicEndpoints(options =>
    {
        // Dynamic routes can't take over the static parts of the application. The admin API and panel reserve their own prefix.
        options.ReservedPrefixes.Add("/swagger");
        options.ReservedPrefixes.Add("/openapi");
        options.OpenApi.Title = "Quick start – dynamic endpoints";
    })
    // Every processor, validator and seeder of this project: GreetingProcessor and QuickStartSeeder.
    .AddFromAssemblyContaining<Program>()
    // Definitions (with history and drafts) in AppDbContext, loaded on start.
    .UseEntityFrameworkStore<AppDbContext>();

// The OpenAPI document of the static API (the admin API) – the dynamic one is generated by DynamicEndpoints.
builder.Services.AddOpenApi();

var app = builder.Build();

// 3. Create the SQLite database on the first start. A real application uses EF Core migrations instead
//    (dotnet ef migrations add …, see docs/articles/ef-core.md).
await using (var scope = app.Services.CreateAsyncScope())
{
    await scope.ServiceProvider.GetRequiredService<AppDbContext>().Database.EnsureCreatedAsync();
}

// 4. The dynamic routes.
app.MapDynamicEndpoints();

// 5. The admin REST API and the panel on top of it. Both are open here – put .RequireAuthorization("admin") on them in real life.
app.MapDynamicEndpointsAdmin("/api/admin/endpoints");
app.MapDynamicEndpointsAdminUI("/admin", adminApiPath: "/api/admin/endpoints", options =>
{
    options.Title = "Quick start";
    options.SwaggerUrl = "/swagger";
    options.OpenApiUrl = "/openapi/dynamic.json";
});

// 6. OpenAPI 3.1 of the dynamic endpoints (always current), the admin API's document, and Swagger UI with both.
app.MapDynamicEndpointsOpenApi("/openapi/dynamic.json");
app.MapOpenApi("/openapi/{documentName}.json");
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/openapi/dynamic.json", "Dynamic endpoints");
    options.SwaggerEndpoint("/openapi/v1.json", "Admin API");
});

app.MapGet("/", () => Results.Redirect("/admin/")).ExcludeFromDescription();

app.Run();

// Makes the entry point visible to WebApplicationFactory in tests/DynamicEndpoints.Samples.Tests.
public partial class Program;
